### ISSUE TITLE
Could you plz upload the rest of the files in the lab document?

### ISSUE THREAD

**Issue by YoungRicky7** [arashsm79/robotics-lab#1]

**Comment by arashsm79** [comment]
Everything should be there. Do you have anything specific that you need?

**Comment by YoungRicky7** [comment]
Oh, I thought some files was missing by looking at the number of the files , thanks for ur reply.&nbsp;


YoungRicky
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arash Sal ***@***.***&gt;; 
发送时间: 2024年3月31日(星期天) 凌晨5:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [arashsm79/robotics-lab] Could you plz upload the rest of the files in the lab document? (Issue #1)














 
Everything should be there. Do you have anything specific that you need?
